googleAnalytics = "UA-121423954-1"
languageCode = "en-ca"
pygmentsCodefences = true
pygmentsStyle = "manni"
theme = "hugo-theme-sam"
title = "Okbrb"
[params]
clickablePhotos = true
dateform = "Mon Jan 02, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 EST"
description = "A new Hugo site."
favicon = "/favicon.ico"
footerText = "okbrb 2018"
galleryFolder = "images/"
homepage = "main"
primaryImage = "/uploads/tn.png"
twitterCard = "summary_large_image"
[[params.mainMenu]]
link = "/projects"
text = "projects"
[[params.mainMenu]]
link = "/about"
text = "about"
